### ISSUE TITLE
ValueInjecter is faster than automapper

### ISSUE THREAD

**Issue by tridip-bba** [omuleanu/ValueInjecter#1]
we know that automapper is a popular value injector. so why people use your ValueInjecter ?
if possible put a comparison between ValueInjecter  and automapper and also discuss all the advantage for which people would like to use ValueInjecter . thanks

**Comment by spyhunter88** [comment]
I think the main difference is the way it work. I search about AutoMapper but it only Map with create new entity in the left side. It can not inject some property from right side to left.
So in the DTO pattern, some property need to be read-only like primary key, create by, create time and important is the way your system works. You don't allow user edit all the properties, but the model include tens of property, you will make you code is big.
I don't know AutoMapper can do that or not and I choose ValueInjecter for now.
