### ISSUE TITLE
Support for .Net 4

### ISSUE THREAD

**Issue by dnlgmzddr** [omuleanu/ValueInjecter#12]
Hi, is there any particular reason to not support .Net 4?

**Comment by omuleanu** [comment]
do you have an app on .net 4 that can't be upgraded to 4.5 ?

**Comment by dnlgmzddr** [comment]
Exactly, I'm  using version 2.3.3. However was there any particular feature in ValueInjecter that requires 4.5?

**Comment by omuleanu** [comment]
not sure, try building it on 4.0
