### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by brgrz** [omuleanu/ValueInjecter#14]
I've been a long time ValueInjecter user however the new version break backwards compatibility. While the changes aren't that hard to implement it still is additional work I'd like to avoid if not necessary.

So what are the new features that make it worthwhile to upgrade? At first glance nothing seems too different. Is it speed maybe?

I haven't seen any articles/blog posts detailing why the new version was implemented at all.

**Comment by omuleanu** [comment]
there's a changelog here: https://github.com/omuleanu/ValueInjecter/blob/master/changelog.txt
showing changes since version 3.0, since source code moved to github
in short there's a Mapper class, and code and performance optimizations
