### ISSUE TITLE
public static TY InjectFromEmpty<TY>(this object source)

### ISSUE THREAD

**Issue by MeTitus** [omuleanu/ValueInjecter#15]
This is more of a pull request than it is an issue, but I can't use git from work so here it goes.
I typically have code like this:

```
(lambda extension method).(x => (SetupField)Activator.CreateInstance<SetupField>().InjectFrom(x))
```

Which could me made easy if the target object was created by ValueInjector. So if you could add a method like:

```
public static TY InjectFromEmpty<TY>(this object source)
{
    return (TY)DefaultInjection.Map(source, Activator.CreateInstance<TY>());
}
```

I could replace the code above with:

```
(lambda extension method).(x => StaticValueInjecter.InjectFromEmpty<SetupField>(x))
```

It makes things a bit more clear I think.

**Comment by omuleanu** [comment]
you could just use Mapper.Map instead

**Comment by MeTitus** [comment]
That did the trick, thanks :P
