### ISSUE TITLE
Add support for .Net 5

### ISSUE THREAD

**Issue by tidusjar** [omuleanu/ValueInjecter#17]
Hello,

I would like to use ValueInjecter in my .Net 5 projects but this is the error I am facing:

```
NU1002 The dependency valueinjecter 3.1.1.2 in project NZBDash.Core does not support framework .NETPlatform,Version=v5.4.
```

Is it possible to add support for .Net 5?

**Comment by omuleanu** [comment]
I think the latest .net version is 4.6

**Comment by tidusjar** [comment]
Sorry I am on about .Net Core (vNext)/ ASP.NET 5

**Comment by omuleanu** [comment]
that one is in rc also, try putting the source code in a separate class library and build it in your solution
