### ISSUE TITLE
Request to support PCL

### ISSUE THREAD

**Issue by Korayem** [omuleanu/ValueInjecter#18]
This nuget is an old friend. Too bad I can't share the love when working on Xamarin projects :(

Update: found that @Xciles made an import for this very reason here: https://github.com/Xciles/PclValueInjecter

**Comment by omuleanu** [comment]
isn't PCL going to be obsolete after .net Core is released ?

**Comment by Korayem** [comment]
Sure but things will take to reflect such changes, especially for those developing on Xamarin where PCL is key
