### ISSUE TITLE
LoopValueInjection removed

### ISSUE THREAD

**Issue by jeanjn** [omuleanu/ValueInjecter#2]
The class LoopValueInjection was removed, but the documentation not have nothing about a substitute.

Witch class replaced LoopValueInjection and witch method I can use instead UseSourceProp?

**Comment by omuleanu** [comment]
you can use LoopInjection https://github.com/omuleanu/ValueInjecter/blob/master/ValueInjecter/Injections/LoopInjection.cs
and override GetTargetProp, MatchTypes, SetValue
in VS when you write override you get suggestions on what you can override
