### ISSUE TITLE
Injecting null properties into string properties is causing object not set to an instance errors

### ISSUE THREAD

**Issue by Korayem** [omuleanu/ValueInjecter#20]
I managed to fix the problem by adding a check that skips properties that are null in `PropertyInjection` class:

```
  protected virtual void Execute(PropertyInfo sp, object source, object target)
        {
            if (sp.CanRead && sp.GetGetMethod() != null && (ignoredProps == null || !ignoredProps.Contains(sp.Name)))
            {
                var tp = target.GetType().GetProperty(sp.Name);
                //Korayem: skip null properties, otherwise its causing exceptions
                if (tp != null && tp.CanWrite && tp.PropertyType == sp.PropertyType && tp.GetSetMethod() != null && sp.GetValue(source, null) != null)
                {
                    tp.SetValue(target, sp.GetValue(source, null), null);
                }
            }
        }
```

Notice `sp.GetValue(source, null) != null` in if condition.

I don't recall facing this issue in v2.x of this nuget

**Comment by omuleanu** [comment]
string can be null, so you should not get errors,
this code would make all injections ignore null values,
you're calling .GetValue twice and that would take a lot more time to execute

**Comment by Korayem** [comment]
Exactly. I've been using ValueInjecter since 2012 and never faced this. My initial impression is _the new version has issues_.  Let me revise my code again between Model and ViewModel injection..

**Comment by Korayem** [comment]
You're correct! I did have something wrong and now its fixed. Thanks!
