### ISSUE TITLE
Issue with Expando dictionary property and VI

### ISSUE THREAD

**Issue by brgrz** [omuleanu/ValueInjecter#21]
I'm doing mapping between two models that both inherit Rick Strahl's Expando (https://weblog.west-wind.com/posts/2012/feb/08/creating-a-dynamic-extensible-c-expando-object).

There's an issue that happens in reflection during injection producing exception 

`System.Reflection.TargetParameterCountException: Parameter count mismatch.`

This started to happen as soon as both classes were made to inherit from Expando. Expando has a property named `Properties`of type `Dictionary<string, object>`.

One of the models originally had property `Dictionary<string, string> Properties` and did not inherit from Expando. When I used to map the other model to this one VI default injecting behaviour obviously skipped this property (and I did the mapping manually in code myself). Now this property was removed in favor of inheriting Expando. The above exception occurs apparently because VI tries to inject between both properties which are now of the same type and name.

The first thing I tried is using the InjectFrom with LoopValueInjection with ignored property like this

`vm.InjectFrom(new LoopInjection(new[] { "Properties" }), query.Model);`

but that didn't help. I am still getting the same exception as if I try the injection without ignoring this property.

I could debug this with VI source code but I wanted to check out here first if anyone has an idea what could be wrong or something else I might try.

**Comment by omuleanu** [comment]
you'll have to debug the source code
