### ISSUE TITLE
ValueInjecter throws AmbiguousMatchException on shadowed properties

### ISSUE THREAD

**Issue by adamhaile** [omuleanu/ValueInjecter#23]
Many value injections in the 3.x version use the Type.GetProperty(string name) method, which throws an AmbiguousMatchException if there are multiple properties with the same name in the hierarchy, i.e. properties shadowed by the 'new' (C#) or 'Shadows' (VB) keyword.

This is a change from 2.3.3, where value injections used the PropertyDescriptorCollection.Find(string name, bool casesensitive) method, which returned the topmost matching property, i..e the one shadowing, not the shadowed one.

We encountered this issue porting a reasonably large application from 2.3.3. to 3.1.1.3.  The existing codebase made extensive use of shadowing to mark limits on how deeply ValueInjecter copied properties.  (I can go into more details if needed.)  

Proposed solution would be either to restore the 2.x behavior (preferable from our standpoint) or, at a minimum, simply ignore shadowed properties.  Currently, any class with shadowed properties is uninjectable.

Thanks for your help.

**Comment by omuleanu** [comment]
please create an unit test showing the problem

**Comment by omuleanu** [comment]
I'm not getting any errors:
```
    public class ShadowPropTest
    {
        public class Foo
        {
            public virtual string Name { get; set; }

            public virtual string Name2 { get; set; }

        }

        public class FooBar : Foo
        {
            public new string Name { get; set; }

            public override string Name2 { get; set; }
        }

        [Test]
        public void ShouldMap()
        {
            var src = new FooBar()
            {
                Name = "abc",
                Name2 = "bce"
            };

            var res = Mapper.Map<FooBar>(src);

            Assert.AreEqual(res.Name, src.Name);
            Assert.AreEqual(res.Name2, src.Name2);
        }
    }
```

**Comment by adamhaile** [comment]
That test passes because both the shadowed and shadowing properties are of the same type, string, so there's not actually an ambiguous match.  

This test fails.  The only change is to make Foo.Name be an int.

```
    public class ShadowPropTest
    {
        public class Foo
        {
            public virtual int Name { get; set; }

            public virtual string Name2 { get; set; }

        }

        public class FooBar : Foo
        {
            public new string Name { get; set; }

            public override string Name2 { get; set; }
        }

        [Test]
        public void ShouldMap() {
            var src = new FooBar() {
                Name = "abc",
                Name2 = "bce"
            };

            var res = Mapper.Map<FooBar>(src);

            Assert.AreEqual(res.Name, src.Name);
            Assert.AreEqual(res.Name2, src.Name2);
        }
    }
```

**Comment by omuleanu** [comment]
@curveship do you have a temp solution ? have you forked this version and made changes  or you're still using 2.3 ?

**Comment by adamhaile** [comment]
Hi Valentin --
We did upgrade to 3.x, but used a tweak of the SameNameType ValueInjection.  It pulls all properties from the target type and takes the first with the same name.  We profiled two versions, one that built up a Dictionary<string, PropertyInfo> indexing the target props by name, one that just looped through the target props looking for a match.  Since the number of items is small (<30 properties in the objects), the iterative approach actually proved faster.

```cs
        public class FirstSameNameType : ValueInjection
        {
            protected override void Inject(object source, object target) {
                var sourceProps = source.GetProps();
                var targetProps = target.GetType().GetTypeInfo().GetProperties();

                foreach (var sp in sourceProps) {
                    if (sp.CanRead && sp.GetGetMethod() != null) {
                        PropertyInfo tp = null;
                        foreach (var _tp in targetProps) {
                            if (_tp.Name == sp.Name) {
                                tp = _tp;
                                break;
                            }
                        }

                        if (tp != null && tp.CanWrite && sp.PropertyType == tp.PropertyType && tp.GetSetMethod() != null) {
                            tp.SetValue(target, sp.GetValue(source, null), null);
                        }
                    }
                }
            }
        }
```

**Comment by omuleanu** [comment]
try this injection instead
```
    public class SameNameType2: ValueInjection
    {
        protected override void Inject(object source, object target)
        {
            var sourceProps = source.GetProps();

            var targetType = target.GetType();

            foreach (var sp in sourceProps)
            {
                if (sp.CanRead && sp.GetGetMethod() != null)
                {
                    var tp = targetType.GetProperty(sp.Name, sp.PropertyType);

                    if (tp != null && tp.CanWrite && sp.PropertyType == tp.PropertyType && tp.GetSetMethod() != null)
                    {
                        tp.SetValue(target, sp.GetValue(source, null), null);
                    }
                }
            }
        }
    }
```
the change is here: `targetType.GetProperty(sp.Name, sp.PropertyType);`

you can change the default injection https://github.com/omuleanu/ValueInjecter#default-injectfrom
