### ISSUE TITLE
(minor) Could it be ValueInjecter instead of valueinjecter?

### ISSUE THREAD

**Issue by shuruev** [omuleanu/ValueInjecter#24]
Hi Valentin,

I looks like "ValueInjecter" name is used consistently across the project/package name, website and documentation:
https://image.prntscr.com/image/eSkgG_-XTKWy9vp7T6klQQ.png

However for package Id in nuspec file it is "valueinjecter", which leads to this:
https://image.prntscr.com/image/crUKaoacSvqtXOnUQodZ6A.png

Is there a specific reason why "valueinjecter" is being used as technical package Id, instead of "ValueInjecter"? Could the package Id be the same "ValueInjecter" as well?

Thank you!

**Comment by omuleanu** [comment]
there is no reason, the package Id should be ValueInjecter

**Comment by shuruev** [comment]
Sounds great, would be nice to get it updated in any of the future releases!
Thank you so much!

**Comment by omuleanu** [comment]
you can try updating now

**Comment by shuruev** [comment]
Now it's working great, thanks!
