### ISSUE TITLE
ValueInjecter is using default mapping and not the custom mapping

### ISSUE THREAD

**Issue by rakeshkhoodeeram** [omuleanu/ValueInjecter#27]
In MappingConfig.Configure I have a custom mapping
```
 CrudMapper.AddMap<Incident, IncidentApiViewModel>((model, tag) =>
{
...
}
```
In my windows application, I have
 `mappedUser = MapperConfig.CrudMapper.Map<Incident,IncidentApiViewModel>(user);
`
Problem is that the default mapping function is being used to assign values. The custom mapping is not being used.

**Comment by omuleanu** [comment]
valueinjecter doesn't have MapperConfig or CrudMapper in ValueInjecter.dll
you might be using a different instance of the mapper than the one you are configuring,
you need to create a unit test to prove/show the issue that your are describing
