### ISSUE TITLE
Loop injection ignored props only applies to parent object; should also apply to children?

### ISSUE THREAD

**Issue by mchew-bdpest** [omuleanu/ValueInjecter#3]
[TestClass]
    public class OmuTest
    {  
         [TestMethod]
        public void CommonMapperOmuDeepCopyIgnoreId()
        {
            ParentProp parentProp = new ParentProp { ANewField = "Hiya", SomeProperty = new SomeProp { aField = 2, bField = "b", Id = 1 }, Id = 3 };
            ParentPropB parentPropB = new ParentPropB();
            parentPropB.InjectFrom(new LoopInjection(new[] { "Id" }), parentProp);
            Assert.AreEqual(parentProp.ANewField, parentPropB.ANewField);
            Assert.AreEqual(0, parentPropB.Id);
            Assert.AreEqual(parentProp.SomeProperty.aField, parentPropB.SomeProperty.aField);
            Assert.AreEqual(parentProp.SomeProperty.bField, parentPropB.SomeProperty.bField);
            // This assert fails with parentPropB.SomeProperty.Id equaling 1
            Assert.AreEqual(0, parentPropB.SomeProperty.Id);
        }
}

```
public class SomeProp
{
    public int Id { get; set; }
    public int aField {get; set;}
    public string bField {get; set;}
}

public class ParentProp
{
    public int Id { get; set; }
    public string ANewField { get; set; }
    public SomeProp SomeProperty { get; set; }
}

public class ParentPropB
{
    public int Id { get; set; }
    public string ANewField { get; set; }
    public SomeProp SomeProperty { get; set; }
}
```

**Comment by omuleanu** [comment]
the InjectFrom will only copy the reference of SomeProperty from one side to the other, think you need to use the Mapper instead, add a map for the types your using and use it
