### ISSUE TITLE
Strong-type InjectFrom API

### ISSUE THREAD

**Issue by doggy8088** [omuleanu/ValueInjecter#32]
I saw one of the example here: https://stackoverflow.com/a/7872469/910074

```cs
IEnumerable<Category> categoryList = categoryService.GetAll();
IList<CategoryViewModel> viewModelList = categoryList
    .Select(x => new CategoryViewModel().InjectFrom(x)).Cast<CategoryViewModel>()
    .ToList();
```

May I ask why the `InjectFrom` API doesn't return a strong-typed `CategoryViewModel`? Why should I have to `Cast` to a type that I already know?

**Comment by omuleanu** [comment]
you could add a strongly typed extension that will do the casting for you:
```     
        public static TTarget InjectFrom<TTarget>(this TTarget target, object source)
        {
            target = (TTarget) DefaultInjection.Map(source, target);
            return target;
        }
```

**Comment by doggy8088** [comment]
@omuleanu I know that. I'm just wondering why don't you just add this feature to ValueInjecter? Any consideration?

**Comment by omuleanu** [comment]
@doggy8088  it will be added
