### ISSUE TITLE
Refactoring from old version to the newest version

### ISSUE THREAD

**Issue by LowieDelneste** [omuleanu/ValueInjecter#4]
Hi

In the latest version you added/removed/renamed some files.
From NuGet:

> added LoopInjection, PropertyInjection
> renamed, refactored KnownSourceInjection, KnownTargetInjection
> removed ConventionInjection, LoopValueInjection, FlatLoopValueInjection, UnflatLoopValueInjection

Now I want to update a previous version of ValueInjecter to the latest version. 
Is it possible to let us know which classes are which? So e.g.: I use the old _ConventionInjection_ class and the old _FlatLoopValueInjection_ class, can I just refactor it to _LoopInjection_ or are there some caveats? 
Can you give us examples what to do when we use an older version and want to use the latest version?

Greetings
Loetn

**Comment by omuleanu** [comment]
yes you should refactor to LoopInjection and FlatLoopInjection, they are not exactly the same as in the older version but it should be easy to refactor
you can look here for examples: https://github.com/omuleanu/ValueInjecter/wiki/custom-injections-examples

**Comment by LowieDelneste** [comment]
Thanks for the fast answer!

So if i'm correct:

> ConventionInjection -> LoopInjection
> FlatLoopValueInjection -> FlatLoopInjection
> LoopValueInjection -> LoopInjection (or ValueInjection?)

Can you provide us a list of the corresponding old vs new classes?

Greetings
Loetn

**Comment by omuleanu** [comment]
yes, you should be able to replace them this way
`LoopInjection` should be all you need most of the time
you can override: 
`string GetTargetProp(string sourceName)` to get the name of the target prop based on the source prop
`bool MatchTypes(Type source, Type target)`
and `SetValue` to cast the source value  and set it into the target prop, or maybe decide not to set it at all
`LoopInjection` also has a constructor with `string[] properties to ignore`
