### ISSUE TITLE
Get Target Property by case insensitive source property name.

### ISSUE THREAD

**Issue by deangoddard** [omuleanu/ValueInjecter#6]
With the legacy class ConventionInjection now obsolete, it broke my code.  Not too big a deal, I'll simply override LoopInjection, and deal with my feature requirements differently.  Love the new refactored framework, however because I need GitHub training, can you please refactor a change on my behalf?

I want to have overriding control over the type.GetProperty() method by passing in a BindingFlag of IgnoreCase.  This has the knock on effect of gaining access to all the features/arguments of the type.GetProperty() method like using attributes.

--- First change ---
In PropertyInjection class replace this line in the Execute() method:
  PropertyInfo property = target.GetType().GetProperty(sp.Name);

With:
  PropertyInfo property = GetTargetProperty(target.GetType(), sp.Name);

And add:
  protected virtual PropertyInfo GetTargetProperty(Type targetType, String spName)
  {
      return targetType.GetProperty(spName);
  }

--- Second Change ---
And  in LoopInjection class replace this line in the Execute() method:
   PropertyInfo property = target.GetType().GetProperty(this.GetTargetProp(sp.Name));

With:
  PropertyInfo property = GetTargetProperty(target.GetType(), GetTargetProp(sp.Name));
## 

This then allows me to create an IgnoreCaseLoopInjection class with the GetTargetProperty() method overridden like this:
protected override PropertyInfo GetTargetProperty(Type targetType, string spName)
{
    return targetType.GetProperty(spName, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.IgnoreCase);
}

**Comment by omuleanu** [comment]
try this:
https://github.com/octocat/Spoon-Knife
https://guides.github.com/activities/forking/index.html

**Comment by omuleanu** [comment]
You can override the Execute method in your custom injection and add the GetTargetProperty method
