### ISSUE TITLE
I can't use ConventionInjection class

### ISSUE THREAD

**Issue by jamadorfi18** [omuleanu/ValueInjecter#7]
Hi, I was trying to inherent ConventionInjection or LoopValueInjection, but I couldn´t use it.

I tried build the project, but the classes are missed.

I´m don´t know If I did something wrong or is an issue, but I can use the InjectFrom method very well.

![conventioninjection](https://cloud.githubusercontent.com/assets/3588874/8684197/477fd014-2a34-11e5-9c47-a16ca9f659bc.png)

**Comment by omuleanu** [comment]
use LoopInjection
ConventionInjection has been removed

**Comment by jamadorfi18** [comment]
Thanks! I´m sorry, I was reading old post about ValueInjecter.
