### ISSUE TITLE
Unable to use ValueInjecter on Universal Application

### ISSUE THREAD

**Issue by AmitBhatnagar24** [omuleanu/ValueInjecter#9]
NuGet package won't install.

...please don't make me use AutoMapper..

Any plans to support universal apps? Please let us know sooner rather than later so we can prepare for our legacy apps that we are updating to universal.

**Comment by omuleanu** [comment]
you can grab the source (fork) and make it work

**Comment by AmitBhatnagar24** [comment]
is this on the planned roadmap for ValueInjecter, or no?

**Comment by omuleanu** [comment]
there's no plan for it atm, we're open to contributions

**Comment by AmitBhatnagar24** [comment]
Turns out this was quite easy... I haven't forked and submitted a pull request yet,.. but all I did was create a Universal class library in VisualStudio, copied all of the original source in, and then used GetTypeInfo() in the places where reflection was needed (i,e:

var hasCompilerGeneratedAttribute = type.GetTypeInfo().GetCustomAttributes(typeof(CompilerGeneratedAttribute), false).ToList().Count > 0;

etc. etc.

My initial test seemed to work just fine..

Just

**Comment by AmitBhatnagar24** [comment]
..had to add the following using statements for it to work:

using System.Reflection;
using System.Runtime.CompilerServices;

.. there was like only 4 changes to make in the code!

**Comment by AmitBhatnagar24** [comment]
please have a look at my pull request.

**Comment by AmitBhatnagar24** [comment]
As requested, I created a new fork and updated the code to work for UWP, as well as added a Universal Windows sample application. 

Check out pull request (https://github.com/omuleanu/ValueInjecter/pull/16)
